import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'SW';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        home: 'Home',
        welcome: 'Welcome back',
        portfolio_balance: 'Total Balance',
        income: 'INCOME',
        expense: 'EXPENSE',
        send: 'Send',
        receive: 'Receive',
        loans: 'Loans',
        score: 'Score',
        transactions: 'Transactions',
        view_all: 'View All',
        active_loan: 'ACTIVE LOAN',
        due_date: 'DUE DATE',
        no_activity: 'No recent activity',
        ussd_mode: 'USSD',
        profile: 'Profile',
        transfer: 'Transfer',
        credit_analysis: 'Credit Analysis',
        settings: 'Settings',
        sign_out: 'Sign Out',
        transaction_history: 'Transaction history',
        all_payments: 'All your payments',
        apply_manage_loans: 'Apply & manage loans',
        live_rates: 'Live exchange rates',
        security_preferences: 'Security & preferences',
        kyc_verified: 'KYC Verified',
        verify_now: 'Verify Now',
        unverified: 'Unverified (Action Required)',
        balance: 'Balance',
        country: 'Country',
        account_type: 'Account Type',
        did_label: 'DIGITAL IDENTITY (DID)',
        ipfs_stored: 'Stored securely on IPFS network',
        receive_funds: 'Receive Funds',
        share_details: 'Share your details to receive money',
        your_phone: 'Your Phone Number',
        your_did: 'Your Financial DID',
        copy: 'Copy',
        copied: 'Copied!',
        scan_qr: 'Scan this code to pay',
        security: 'Security',
        notifications: 'Notifications',
        app_info: 'App Information',
        change_pin: 'Change PIN',
        privacy_mode: 'Privacy Mode',
        push_notifications: 'Push Notifications',
        email_alerts: 'Email Alerts',
        version: 'Version',
        build: 'Build',
        instant_loans: 'Instant Loans',
        credit_limit: 'Credit Limit',
        interest: 'Interest',
        borrow_funds: 'Borrow Funds',
        active_repayment: 'ACTIVE REPAYMENT',
        repayable: 'Repayable',
        repay_now: 'Repay Now',
        loan_history: 'Loan History',
        no_past_loans: 'No past loans',
        request_loan: 'Request Loan',
        principal_amount: 'Principal Amount',
        limit: 'Limit',
        purpose: 'Purpose',
        duration: 'Duration',
        days: 'Days',
        confirm_request: 'Confirm Request',
        processing: 'Processing',
        repayment: 'Repayment',
        wallet_balance: 'Wallet Balance',
        payment_amount: 'Payment Amount',
        verifying: 'Verifying',
        pay_with_wallet: 'Pay with Wallet',
        transfer_success: 'Transfer Success',
        deducted_from_wallet: 'Deducted from your wallet',
        recipient: 'Recipient',
        tx_hash: 'Transaction Hash',
        done_btn: 'Done',
        recipient_details: 'Recipient Details',
        transfer_amount: 'Transfer Amount',
        note_optional: 'Note (Optional)',
        what_is_this_for: 'What is this for?',
        initial_amount: 'Initial Amount',
        network_fee: 'Network Fee',
        total_cost: 'Total Cost',
        review_transaction: 'Review Transaction',
        review_order: 'Review Order',
        transferring_to: 'Transferring to',
        net_amount: 'Net Amount',
        service_fee: 'Service Fee',
        settlement: 'Settlement',
        network: 'Network',
        final_total: 'Final Total',
        confirm_authorize: 'Confirm & Authorize',
        cancel_edit: 'Cancel & Edit',
        initiating_transfer: 'Initiating Transfer...',
        global: 'Global',
        all_filter: 'All',
        sent_filter: 'Sent',
        received_filter: 'Received',
        cross_border_filter: 'Cross-border',
        loans_filter: 'Loans',
        loan_disbursed: 'Loan disbursed',
        from: 'From',
        to: 'To',
        success_badge: 'Success',
        pending_badge: 'Pending',
        active_trust_score: 'Active Trust Score',
        ranking: 'Ranking',
        top_ranking: 'Top 15%',
        poor: 'POOR',
        average: 'AVERAGE',
        excellent: 'EXCELLENT',
        available_credit: 'Available Credit',
        fixed_rate: 'Fixed Rate',
        repayment_period: 'Repayment in 30 days',
        impact_factors: 'Impact Factors',
        improve_score: 'Improve Your Score',
        tip_1: 'Process transfers regularly to build a transaction history',
        tip_2: 'Repay loans on time — each settlement adds +30 points',
        tip_3: 'Account tenure matters; keep your wallet active monthly',
        tip_4: 'Consistent usage across all services boosts credibility',
        grade_excellent: 'Excellent',
        grade_good: 'Good',
        grade_fair: 'Fair',
        grade_building: 'Building',
        offline_mode: 'Offline Mode',
        ussd_menu: 'SAFARIPAY MENU:',
        enter_choice: 'Enter choice (1-5):',
        enter_phone: 'ENTER PHONE:',
        enter_amount: 'ENTER AMOUNT:',
        confirm_send_ussd: 'SEND {amount} TO {recipient}?',
        yes: '1. Yes',
        no: '2. No',
        wallet_balance_ussd: 'Your wallet balance is:',
        dial_0_back: 'Dial 0 to go back',
        trust_score_ussd: 'TRUST SCORE:',
        grade_ussd: 'GRADE:',
        repay_boost: 'Repay loans to boost score.',
        offline_gateway: 'Offline Gateway',
        offline_desc: 'SafariPay uses USSD technology to serve rural populations without internet. The menus above simulate the actual experience on a feature phone.',
        current_command: 'Current Command: *150#',
        login_btn: 'Sign in',
        join_btn: 'Join now',
        full_name: 'Full name',
        phone_number: 'Phone number',
        create_account: 'Create account',
        continue_btn: 'Continue',
        enter_pin: 'Enter your PIN',
        create_pin: 'Create a 4-digit PIN',
        confirm_pin: 'Confirm your PIN',
        back: 'Back',
        offline_support: 'Offline Support',
        receive_offline_desc: 'You can also receive funds via USSD. Tell the sender to dial 1 on their SafariPay USSD menu and enter your phone number.',
        active_badge: 'Active',
        withdraw: 'Withdraw',
        send_method: 'Select Method',
        safari_transfer: 'SafariPay User',
        mobile_money: 'Mobile Money',
        bank_transfer: 'Bank Transfer',
        select_provider: 'Select Provider',
        select_bank: 'Select Bank',
        withdraw_funds: 'Withdraw Funds',
        withdraw_to: 'Withdraw To',
        withdraw_success: 'Withdrawal Successful',
        withdraw_processing: 'Withdrawal Processing...',
        mpesa: 'Vodacom M-Pesa',
        airtel: 'Airtel Money',
        halopesa: 'Halopesa',
        tigo: 'Tigo Pesa',
        crdb: 'CRDB Bank',
        nmb: 'NMB Bank',
        other_bank: 'Other Bank',
        account_number: 'Account Number',
        withdraw_amount: 'Withdrawal Amount',
        confirm_withdraw: 'Confirm Withdrawal',
        forgot_pin: 'Forgot PIN',
        unlock_withdrawal: 'Unlock Withdrawal (Level 1)',
        reach_level_1: 'Reach Level 1 to unlock full borrowing capacity',
        elig_identity: 'Identity Verified',
        elig_p2p: '3+ P2P Transfers',
        elig_balance: 'Hold minimum balance for 48h',
        loan_reward_msg: 'Welcome Reward',
        amount_paid: 'Amount Paid',
        amount_remaining: 'Remaining to Pay',
        total_to_repay: 'Total to Repay',
        hold_funds_msg: 'Perform more transactions and hold balance to withdraw',
        starter_limit_msg: 'New users are limited to {amount}. Complete requirements to unlock full limit.',
        repaid: 'Repaid',
        paid_badge: 'Paid',
        remaining_badge: 'Remaining',
        received_from: 'Received from',
        sent_to: 'Sent to',
        welcome_reward_title: 'Welcome Reward! 🎁',
        welcome_reward_body: 'You received {amount} as a welcome gift!',
        welcome_reward_toast: 'Welcome to SafariPay! Here is your {amount} reward. 🎁',
        fee_credit: 'Fee Credit (Makato)',
        fee_credit_hint: 'Keep transacting to earn more fee credits!',
        muongozo_level1: 'Guide to Level 1',
        enter_transfer_pin: 'Enter Security PIN',
        enter_pin_msg: 'To authorize this transfer, please enter your 4-digit security PIN.',
        save_favorite: 'Save as Favorite',
        nickname_placeholder: 'Nickname (e.g. Mama, Bro)',
        favorites_title: 'Favorite Contacts',
        confirm_transfer: 'Confirm Transfer',
        offline_mode_active: 'Offline Mode Active',
        no_internet_msg: 'Transfers will sync when online',
        syncing_transactions: 'Syncing transactions...',
        remaining: 'remaining',
        provisioning_wallet: 'Provisioning Your Wallet...',
        provisioning_msg: 'SafariPay is securing your identity and creating your digital wallet in the background.',
        waiting_for_network: 'Waiting for network signal...'
    },
    SW: {
        home: 'Nyumbani',
        welcome: 'Karibu tena',
        portfolio_balance: 'Jumla ya Salio',
        income: 'MAPATO',
        expense: 'MATUMIZI',
        send: 'Tuma',
        receive: 'Pokea',
        loans: 'Mikopo',
        score: 'Alama',
        transactions: 'Miamala',
        view_all: 'Tazama Zote',
        active_loan: 'MKOPO AMILIFU',
        due_date: 'TAREHE YA MALIPO',
        no_activity: 'Hakuna miamala hivi karibuni',
        ussd_mode: 'USSD',
        profile: 'Wasifu',
        transfer: 'Uhamisho',
        credit_analysis: 'Uchambuzi wa Mikopo',
        settings: 'Mipangilio',
        sign_out: 'Ondoka',
        transaction_history: 'Historia ya miamala',
        all_payments: 'Malipo yako yote',
        apply_manage_loans: 'Omba & dhibiti mikopo',
        live_rates: 'Viwango vya kubadilisha fedha',
        security_preferences: 'Usalama & mapendeleo',
        kyc_verified: 'KYC Imethibitishwa',
        verify_now: 'Thibitisha Sasa',
        unverified: 'Hajathibitishwa (Chukua Hatua)',
        balance: 'Salio',
        country: 'Nchi',
        account_type: 'Aina ya Akaunti',
        did_label: 'IDHINI YA KIDIGITALI (DID)',
        ipfs_stored: 'Imehifadhiwa salama kwenye mtandao wa IPFS',
        receive_funds: 'Pokea Fedha',
        share_details: 'Shiriki maelezo yako kupokea pesa',
        your_phone: 'Namba yako ya Simu',
        your_did: 'ID yako ya DID ya Kifedha',
        copy: 'Nakili',
        copied: 'Imenakiliwa!',
        scan_qr: 'Skeni kodi hii kulipa',
        security: 'Usalama',
        notifications: 'Taarifa',
        app_info: 'Taarifa za App',
        change_pin: 'Badilisha PIN',
        privacy_mode: 'Hali ya Kuficha',
        push_notifications: 'Taarifa za Push',
        email_alerts: 'Taarifa za Barua pepe',
        version: 'Toleo',
        build: 'Jengo',
        instant_loans: 'Mikopo ya Papo Hapo',
        credit_limit: 'Kikomo cha Mkopo',
        interest: 'Riba',
        borrow_funds: 'Kopa Fedha',
        active_repayment: 'REJESHO AMILIFU',
        repayable: 'Kiwango cha Kurejesha',
        repay_now: 'Lipa Sasa',
        loan_history: 'Historia ya Mikopo',
        no_past_loans: 'Hakuna mikopo ya zamani',
        request_loan: 'Omba Mkopo',
        principal_amount: 'Kiasi cha Mkopo',
        limit: 'Kikomo',
        purpose: 'Madhumuni',
        duration: 'Muda',
        days: 'Siku',
        confirm_request: 'Thibitisha Ombi',
        processing: 'Inashughulikiwa...',
        repayment: 'Marejesho',
        wallet_balance: 'Salio la Wallet',
        payment_amount: 'Kiasi cha Malipo',
        verifying: 'Inathibitishwa...',
        pay_with_wallet: 'Lipa kwa Wallet',
        transfer_success: 'Uhamisho Umefanikiwa',
        deducted_from_wallet: 'Imekatwa kutoka kwenye wallet yako',
        recipient: 'Mpokeaji',
        tx_hash: 'Kodi ya Muamala (Hash)',
        done_btn: 'Imekamilika',
        recipient_details: 'Maelezo ya Mpokeaji',
        transfer_amount: 'Kiasi cha Uhamisho',
        note_optional: 'Maelezo (Sio lazima)',
        what_is_this_for: 'Hii ni ya nini?',
        initial_amount: 'Kiasi cha Awali',
        network_fee: 'Gharama ya Mtandao',
        total_cost: 'Gharama Kamili',
        review_transaction: 'Kagua Muamala',
        review_order: 'Kagua Agizo',
        transferring_to: 'Unatuma kwenda kwa',
        net_amount: 'Kiasi Halisi',
        service_fee: 'Gharama ya Huduma',
        settlement: 'Malipo ya Papo hapo',
        network: 'Mtandao',
        final_total: 'Jumla ya Mwisho',
        confirm_authorize: 'Thibitisha & Ruhusu',
        cancel_edit: 'Ghairi & Hariri',
        initiating_transfer: 'Muamala unaanza...',
        global: 'Kimataifa',
        all_filter: 'Zote',
        sent_filter: 'Zilizotumwa',
        received_filter: 'Zilizopokelewa',
        cross_border_filter: 'Mpakani',
        loans_filter: 'Mikopo',
        loan_disbursed: 'Mkopo umetolewa',
        from: 'Kutoka kwa',
        to: 'Kwenda kwa',
        success_badge: 'Imefanikiwa',
        pending_badge: 'Inasubiri',
        active_trust_score: 'Alama ya Uaminifu',
        ranking: 'Nafasi',
        top_ranking: 'Asilimia 15 ya Juu',
        poor: 'MBOVU',
        average: 'WASTANI',
        excellent: 'BORA SANA',
        available_credit: 'Mkopo Unaopatikana',
        fixed_rate: 'Riba Isiyobadilika',
        repayment_period: 'Malipo ndani ya siku 30',
        impact_factors: 'Vitu Vinavyoathiri',
        improve_score: 'Boresha Alama Zako',
        tip_1: 'Fanya miamala mara kwa mara ili kujenga historia ya kifedha',
        tip_2: 'Lipa mikopo kwa wakati — kila marejesho yanaongeza alama +30',
        tip_3: 'Muda wa akaunti ni muhimu; tumia wallet yako kila mwezi',
        tip_4: 'Matumizi ya huduma zote mara kwa mara yanaongeza uaminifu',
        grade_excellent: 'Bora Sana',
        grade_good: 'Nzuri',
        grade_fair: 'Wastani',
        grade_building: 'Inajengeka',
        offline_mode: 'Hali ya Nje ya Mtandao',
        ussd_menu: 'MENU YA SAFARIPAY:',
        enter_choice: 'Ingiza chaguo (1-5):',
        enter_phone: 'INGIZA NAMBA:',
        enter_amount: 'INGIZA KIASI:',
        confirm_send_ussd: 'TUMA {amount} KWENDA {recipient}?',
        yes: '1. Ndiyo',
        no: '2. Hapana',
        wallet_balance_ussd: 'Salio la wallet yako ni:',
        dial_0_back: 'Piga 0 kurudi nyuma',
        trust_score_ussd: 'ALAMA YA UAMINIFU:',
        grade_ussd: 'DARAJA:',
        repay_boost: 'Lipa mikopo kuongeza alama.',
        offline_gateway: 'Lango la Nje ya Mtandao',
        offline_desc: 'SafariPay inatumia teknolojia ya USSD kuhudumia wananchi wa vijijini wasio na internet. Menu hizi zinaonyesha jinsi huduma inavyofanya kazi kwenye simu ya kawaida.',
        current_command: 'Amri ya Sasa: *150#',
        login_btn: 'Ingia',
        join_btn: 'Jiunge sasa',
        full_name: 'Jina kamili',
        phone_number: 'Namba ya simu',
        create_account: 'Tengeneza akaunti',
        continue_btn: 'Endelea',
        enter_pin: 'Ingiza PIN yako',
        create_pin: 'Tengeneza PIN ya namba 4',
        confirm_pin: 'Thibitisha PIN yako',
        back: 'Nyuma',
        offline_support: 'Msaada Bila Mtandao',
        receive_offline_desc: 'Unaweza pia kupokea pesa kupitia USSD. Mwambie mtumaji apige 1 kwenye menyu ya USSD ya SafariPay na apeleke namba yako ya simu.',
        active_badge: 'Amilifu',
        withdraw: 'Toa',
        send_method: 'Chagua Njia',
        safari_transfer: 'Mtumiaji wa SafariPay',
        mobile_money: 'Pesa kwa Simu',
        bank_transfer: 'Benki',
        select_provider: 'Chagua Mtoa Huduma',
        select_bank: 'Chagua Benki',
        withdraw_funds: 'Toa Fedha',
        withdraw_to: 'Toa Kwenda',
        withdraw_success: 'Utoaji Umefanikiwa',
        withdraw_processing: 'Utoaji unashughulikiwa...',
        mpesa: 'Vodacom M-Pesa',
        airtel: 'Airtel Money',
        halopesa: 'Halopesa',
        tigo: 'Tigo Pesa',
        crdb: 'CRDB Benki',
        nmb: 'NMB Benki',
        other_bank: 'Benki Nyingine',
        account_number: 'Namba ya Akaunti',
        withdraw_amount: 'Kiasi cha Kutoa',
        confirm_withdraw: 'Thibitisha Utoaji',
        forgot_pin: 'Umesahau PIN',
        unlock_withdrawal: 'Fungua Huduma ya Kutoa (Level 1)',
        reach_level_1: 'Fika Level 1 ili uweze kutoa mkopo wako kikamilifu',
        elig_identity: 'ID Imethibitishwa',
        elig_p2p: 'Miamala 3+ ya Kutuma',
        elig_balance: 'Weka akiba ya kutosha kwa Masaa 48',
        loan_reward_msg: 'Zawadi ya Kujiunga',
        amount_paid: 'Kiasi Kilicholipwa',
        amount_remaining: 'Baki ya Kurejesha',
        total_to_repay: 'Jumla ya Kurejesha',
        hold_funds_msg: 'Fanya miamala zaidi na weka akiba ili uweze kutoa',
        starter_limit_msg: 'Watumiaji wapya wana kikomo cha {amount}. Kamilisha vigezo kufungua kikomo chote.',
        repaid: 'Imerejeshwa',
        paid_badge: 'Imelipwa',
        remaining_badge: 'Iliyobaki',
        received_from: 'Imepokelewa kutoka kwa',
        sent_to: 'Imetumwa kwa',
        welcome_reward_title: 'Zawadi ya Karibu! 🎁',
        welcome_reward_body: 'Umepokea {amount} kama zawadi ya ukaribisho!',
        welcome_reward_toast: 'Karibu SafariPay! Hii hapa ni zawadi yako ya {amount}. 🎁',
        fee_credit: 'Akiba ya Tozo (Makato)',
        fee_credit_hint: 'Endelea kufanya miamala ili upate bonasi zaidi!',
        muongozo_level1: 'Mwongozo wa Level ya 1',
        enter_transfer_pin: 'Ingiza PIN ya Siri',
        enter_pin_msg: 'Ili kukamilisha muamala huu, tafadhali ingiza PIN yako ya siri ya namba 4.',
        save_favorite: 'Hifadhi Kama Rafiki',
        nickname_placeholder: 'Jina (mfn: Mama, Kaka)',
        favorites_title: 'Marafiki wa Karibu',
        confirm_transfer: 'Thibitisha Muamala',
        offline_mode_active: 'Njia ya Offline IKO Amilifu',
        no_internet_msg: 'Miamala itasawazishwa ukipata mtandao',
        syncing_transactions: 'Tunasawazisha miamala...',
        remaining: 'itakayobaki',
        provisioning_wallet: 'Tunatengeneza Wallet Yako...',
        provisioning_msg: 'SafariPay inahifadhi utambulisho wako na kutengeneza wallet yako ya kidigitali.',
        waiting_for_network: 'Tunasubiri mawasiliano ya mtandao...'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        return (localStorage.getItem('safari_lang') as Language) || 'EN';
    });

    useEffect(() => {
        localStorage.setItem('safari_lang', language);
    }, [language]);

    const t = (key: string | undefined) => {
        if (!key) return '';
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
